### ISSUE TITLE
Remove AWS Provider lock

### ISSUE THREAD

**Issue by rhoboat** [gruntwork-io/cloud-chasers#24]
### Full list of repos to unlock

Refer to #1 and the [Notion table](https://www.notion.so/gruntwork/AWS-Provider-4-0-Upgrade-2167fed8391a4d4aa94c241988e90d1c).

- https://github.com/gruntwork-io/intro-to-terraform/pull/26 (don't release)
- https://github.com/gruntwork-io/terraform-aws-ci/pull/444
- https://github.com/gruntwork-io/terraform-aws-utilities/pull/58/
- https://github.com/gruntwork-io/terraform-aws-vpc/pull/273
  - Compatibility updates in https://github.com/gruntwork-io/terraform-aws-vpc/releases/tag/v0.21.0
- https://github.com/gruntwork-io/terraform-aws-asg/pull/150
- https://github.com/gruntwork-io/terraform-aws-security/pull/660
  - Compatibility updates in https://github.com/gruntwork-io/terraform-aws-security/releases/tag/v0.63.0
- https://github.com/gruntwork-io/terraform-aws-data-storage/pull/256
- https://github.com/gruntwork-io/terraform-aws-static-assets/pull/102 or https://github.com/gruntwork-io/terraform-aws-static-assets/pull/103
  - Compatibility updates in https://github.com/gruntwork-io/terraform-aws-static-assets/releases/tag/v0.14.0
- https://github.com/gruntwork-io/terraform-aws-monitoring/pull/251
  - Compatibility updates in https://github.com/gruntwork-io/terraform-aws-monitoring/releases/tag/v0.33.0
- https://github.com/gruntwork-io/terraform-aws-monitoring/pull/257
- https://github.com/gruntwork-io/terraform-aws-openvpn/pull/193 or https://github.com/gruntwork-io/terraform-aws-openvpn/pull/196
  - Compatibility updates in https://github.com/gruntwork-io/terraform-aws-openvpn/releases/tag/v0.23.0
- https://github.com/gruntwork-io/terraform-aws-lambda/pull/138
  - Upgrade test PR is https://github.com/gruntwork-io/terraform-aws-lambda/pull/145 
- https://github.com/gruntwork-io/terraform-aws-server/pull/163
  - Follow up https://github.com/gruntwork-io/terraform-aws-server/pull/177
- https://github.com/gruntwork-io/terraform-aws-load-balancer/pull/152
  - Follow up https://github.com/gruntwork-io/terraform-aws-load-balancer/pull/160
- https://github.com/gruntwork-io/terraform-aws-cache/pull/80
  - Follow up https://github.com/gruntwork-io/terraform-aws-cache/pull/84
- https://github.com/gruntwork-io/terraform-aws-messaging/pull/81
  - Follow up https://github.com/gruntwork-io/terraform-aws-messaging/pull/84
- https://github.com/gruntwork-io/terraform-aws-ecs/pull/352
- https://github.com/gruntwork-io/terraform-aws-eks/pull/436
- https://github.com/gruntwork-io/terraform-aws-cis-service-catalog/pull/426 (Assignee: @yorinasub17 )
- https://github.com/gruntwork-io/terraform-aws-service-catalog/pull/1454
  - gruntwork-io/terraform-aws-service-catalog#1593 Partially implemented (just landingzone modules, prioritized for a customer)
  - No need for upgrade tests!

**Comment by yorinasub17** [comment]
FYI @rhoboat , Service catalog has partial unlock (just the landing zone modules), which was prioritized for a customer per https://github.com/gruntwork-io/knowledge-base/discussions/487
